/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.coinex.dex.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreateOrderInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-09T11:28:51.986+08:00")
public class CreateOrderInfo {
  @SerializedName("order_id")
  private String orderId = null;

  @SerializedName("sender")
  private String sender = null;

  @SerializedName("trading_pair")
  private String tradingPair = null;

  @SerializedName("order_type")
  private Integer orderType = null;

  @SerializedName("price")
  private String price = null;

  @SerializedName("quantity")
  private Long quantity = null;

  @SerializedName("side")
  private Integer side = null;

  @SerializedName("time_in_force")
  private Integer timeInForce = null;

  @SerializedName("feature_fee")
  private Long featureFee = null;

  @SerializedName("height")
  private Long height = null;

  @SerializedName("frozen_fee")
  private Long frozenFee = null;

  @SerializedName("freeze")
  private Long freeze = null;

  @SerializedName("tx_hash")
  private String txHash = null;

  public CreateOrderInfo orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @ApiModelProperty(example = "coinex1nv3ghvdnpgc28mvjfkyrle5ccx0m3vesqp8tdx-1", value = "")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public CreateOrderInfo sender(String sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Get sender
   * @return sender
  **/
  @ApiModelProperty(value = "")
  public String getSender() {
    return sender;
  }

  public void setSender(String sender) {
    this.sender = sender;
  }

  public CreateOrderInfo tradingPair(String tradingPair) {
    this.tradingPair = tradingPair;
    return this;
  }

   /**
   * Get tradingPair
   * @return tradingPair
  **/
  @ApiModelProperty(example = "abc/cet", value = "")
  public String getTradingPair() {
    return tradingPair;
  }

  public void setTradingPair(String tradingPair) {
    this.tradingPair = tradingPair;
  }

  public CreateOrderInfo orderType(Integer orderType) {
    this.orderType = orderType;
    return this;
  }

   /**
   * Limited value 2
   * @return orderType
  **/
  @ApiModelProperty(example = "2", value = "Limited value 2")
  public Integer getOrderType() {
    return orderType;
  }

  public void setOrderType(Integer orderType) {
    this.orderType = orderType;
  }

  public CreateOrderInfo price(String price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @ApiModelProperty(example = "0", value = "")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public CreateOrderInfo quantity(Long quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @ApiModelProperty(example = "0", value = "")
  public Long getQuantity() {
    return quantity;
  }

  public void setQuantity(Long quantity) {
    this.quantity = quantity;
  }

  public CreateOrderInfo side(Integer side) {
    this.side = side;
    return this;
  }

   /**
   * BUY:1/SELL:2
   * @return side
  **/
  @ApiModelProperty(example = "1", value = "BUY:1/SELL:2")
  public Integer getSide() {
    return side;
  }

  public void setSide(Integer side) {
    this.side = side;
  }

  public CreateOrderInfo timeInForce(Integer timeInForce) {
    this.timeInForce = timeInForce;
    return this;
  }

   /**
   * GTE:3/IOC:4
   * @return timeInForce
  **/
  @ApiModelProperty(example = "3", value = "GTE:3/IOC:4")
  public Integer getTimeInForce() {
    return timeInForce;
  }

  public void setTimeInForce(Integer timeInForce) {
    this.timeInForce = timeInForce;
  }

  public CreateOrderInfo featureFee(Long featureFee) {
    this.featureFee = featureFee;
    return this;
  }

   /**
   * Order feature fee, sato.CET as the unit
   * @return featureFee
  **/
  @ApiModelProperty(example = "0", value = "Order feature fee, sato.CET as the unit")
  public Long getFeatureFee() {
    return featureFee;
  }

  public void setFeatureFee(Long featureFee) {
    this.featureFee = featureFee;
  }

  public CreateOrderInfo height(Long height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @ApiModelProperty(example = "0", value = "")
  public Long getHeight() {
    return height;
  }

  public void setHeight(Long height) {
    this.height = height;
  }

  public CreateOrderInfo frozenFee(Long frozenFee) {
    this.frozenFee = frozenFee;
    return this;
  }

   /**
   * Order frozen fee, sato.CET as the unit
   * @return frozenFee
  **/
  @ApiModelProperty(example = "0", value = "Order frozen fee, sato.CET as the unit")
  public Long getFrozenFee() {
    return frozenFee;
  }

  public void setFrozenFee(Long frozenFee) {
    this.frozenFee = frozenFee;
  }

  public CreateOrderInfo freeze(Long freeze) {
    this.freeze = freeze;
    return this;
  }

   /**
   * Freeze sato.CET amount
   * @return freeze
  **/
  @ApiModelProperty(example = "0", value = "Freeze sato.CET amount")
  public Long getFreeze() {
    return freeze;
  }

  public void setFreeze(Long freeze) {
    this.freeze = freeze;
  }

  public CreateOrderInfo txHash(String txHash) {
    this.txHash = txHash;
    return this;
  }

   /**
   * The tx hash
   * @return txHash
  **/
  @ApiModelProperty(value = "The tx hash")
  public String getTxHash() {
    return txHash;
  }

  public void setTxHash(String txHash) {
    this.txHash = txHash;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateOrderInfo createOrderInfo = (CreateOrderInfo) o;
    return Objects.equals(this.orderId, createOrderInfo.orderId) &&
        Objects.equals(this.sender, createOrderInfo.sender) &&
        Objects.equals(this.tradingPair, createOrderInfo.tradingPair) &&
        Objects.equals(this.orderType, createOrderInfo.orderType) &&
        Objects.equals(this.price, createOrderInfo.price) &&
        Objects.equals(this.quantity, createOrderInfo.quantity) &&
        Objects.equals(this.side, createOrderInfo.side) &&
        Objects.equals(this.timeInForce, createOrderInfo.timeInForce) &&
        Objects.equals(this.featureFee, createOrderInfo.featureFee) &&
        Objects.equals(this.height, createOrderInfo.height) &&
        Objects.equals(this.frozenFee, createOrderInfo.frozenFee) &&
        Objects.equals(this.freeze, createOrderInfo.freeze) &&
        Objects.equals(this.txHash, createOrderInfo.txHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, sender, tradingPair, orderType, price, quantity, side, timeInForce, featureFee, height, frozenFee, freeze, txHash);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateOrderInfo {\n");
    
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    tradingPair: ").append(toIndentedString(tradingPair)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    side: ").append(toIndentedString(side)).append("\n");
    sb.append("    timeInForce: ").append(toIndentedString(timeInForce)).append("\n");
    sb.append("    featureFee: ").append(toIndentedString(featureFee)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    frozenFee: ").append(toIndentedString(frozenFee)).append("\n");
    sb.append("    freeze: ").append(toIndentedString(freeze)).append("\n");
    sb.append("    txHash: ").append(toIndentedString(txHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

