/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.coinex.dex.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.coinex.dex.client.model.BaseReq;
import org.coinex.dex.client.model.Coin;

/**
 * Delegation2
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-28T12:10:24.313+08:00")
public class Delegation2 {
  @SerializedName("base_req")
  private BaseReq baseReq = null;

  @SerializedName("delegator_address")
  private String delegatorAddress = null;

  @SerializedName("validator_src_address")
  private String validatorSrcAddress = null;

  @SerializedName("validator_dst_address")
  private String validatorDstAddress = null;

  @SerializedName("amount")
  private Coin amount = null;

  public Delegation2 baseReq(BaseReq baseReq) {
    this.baseReq = baseReq;
    return this;
  }

   /**
   * Get baseReq
   * @return baseReq
  **/
  @ApiModelProperty(required = true, value = "")
  public BaseReq getBaseReq() {
    return baseReq;
  }

  public void setBaseReq(BaseReq baseReq) {
    this.baseReq = baseReq;
  }

  public Delegation2 delegatorAddress(String delegatorAddress) {
    this.delegatorAddress = delegatorAddress;
    return this;
  }

   /**
   * Get delegatorAddress
   * @return delegatorAddress
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDelegatorAddress() {
    return delegatorAddress;
  }

  public void setDelegatorAddress(String delegatorAddress) {
    this.delegatorAddress = delegatorAddress;
  }

  public Delegation2 validatorSrcAddress(String validatorSrcAddress) {
    this.validatorSrcAddress = validatorSrcAddress;
    return this;
  }

   /**
   * Get validatorSrcAddress
   * @return validatorSrcAddress
  **/
  @ApiModelProperty(required = true, value = "")
  public String getValidatorSrcAddress() {
    return validatorSrcAddress;
  }

  public void setValidatorSrcAddress(String validatorSrcAddress) {
    this.validatorSrcAddress = validatorSrcAddress;
  }

  public Delegation2 validatorDstAddress(String validatorDstAddress) {
    this.validatorDstAddress = validatorDstAddress;
    return this;
  }

   /**
   * Get validatorDstAddress
   * @return validatorDstAddress
  **/
  @ApiModelProperty(required = true, value = "")
  public String getValidatorDstAddress() {
    return validatorDstAddress;
  }

  public void setValidatorDstAddress(String validatorDstAddress) {
    this.validatorDstAddress = validatorDstAddress;
  }

  public Delegation2 amount(Coin amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(required = true, value = "")
  public Coin getAmount() {
    return amount;
  }

  public void setAmount(Coin amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Delegation2 delegation2 = (Delegation2) o;
    return Objects.equals(this.baseReq, delegation2.baseReq) &&
        Objects.equals(this.delegatorAddress, delegation2.delegatorAddress) &&
        Objects.equals(this.validatorSrcAddress, delegation2.validatorSrcAddress) &&
        Objects.equals(this.validatorDstAddress, delegation2.validatorDstAddress) &&
        Objects.equals(this.amount, delegation2.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baseReq, delegatorAddress, validatorSrcAddress, validatorDstAddress, amount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Delegation2 {\n");
    
    sb.append("    baseReq: ").append(toIndentedString(baseReq)).append("\n");
    sb.append("    delegatorAddress: ").append(toIndentedString(delegatorAddress)).append("\n");
    sb.append("    validatorSrcAddress: ").append(toIndentedString(validatorSrcAddress)).append("\n");
    sb.append("    validatorDstAddress: ").append(toIndentedString(validatorDstAddress)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

