/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.coinex.dex.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * FillOrderInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-09T11:28:51.986+08:00")
public class FillOrderInfo {
  @SerializedName("order_id")
  private String orderId = null;

  @SerializedName("trading_pair")
  private String tradingPair = null;

  @SerializedName("height")
  private Long height = null;

  @SerializedName("side")
  private Integer side = null;

  @SerializedName("price")
  private String price = null;

  @SerializedName("left_stock")
  private Long leftStock = null;

  @SerializedName("freeze")
  private Long freeze = null;

  @SerializedName("deal_stock")
  private Long dealStock = null;

  @SerializedName("deal_money")
  private Long dealMoney = null;

  @SerializedName("curr_stock")
  private Long currStock = null;

  @SerializedName("curr_money")
  private Long currMoney = null;

  public FillOrderInfo orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @ApiModelProperty(example = "coinex1nv3ghvdnpgc28mvjfkyrle5ccx0m3vesqp8tdx-1", value = "")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public FillOrderInfo tradingPair(String tradingPair) {
    this.tradingPair = tradingPair;
    return this;
  }

   /**
   * Get tradingPair
   * @return tradingPair
  **/
  @ApiModelProperty(example = "abc/cet", value = "")
  public String getTradingPair() {
    return tradingPair;
  }

  public void setTradingPair(String tradingPair) {
    this.tradingPair = tradingPair;
  }

  public FillOrderInfo height(Long height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @ApiModelProperty(example = "0", value = "")
  public Long getHeight() {
    return height;
  }

  public void setHeight(Long height) {
    this.height = height;
  }

  public FillOrderInfo side(Integer side) {
    this.side = side;
    return this;
  }

   /**
   * BUY:1/SELL:2
   * @return side
  **/
  @ApiModelProperty(example = "1", value = "BUY:1/SELL:2")
  public Integer getSide() {
    return side;
  }

  public void setSide(Integer side) {
    this.side = side;
  }

  public FillOrderInfo price(String price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @ApiModelProperty(example = "0", value = "")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public FillOrderInfo leftStock(Long leftStock) {
    this.leftStock = leftStock;
    return this;
  }

   /**
   * Order left stock
   * @return leftStock
  **/
  @ApiModelProperty(example = "0", value = "Order left stock")
  public Long getLeftStock() {
    return leftStock;
  }

  public void setLeftStock(Long leftStock) {
    this.leftStock = leftStock;
  }

  public FillOrderInfo freeze(Long freeze) {
    this.freeze = freeze;
    return this;
  }

   /**
   * Freeze sato.CET amount
   * @return freeze
  **/
  @ApiModelProperty(example = "0", value = "Freeze sato.CET amount")
  public Long getFreeze() {
    return freeze;
  }

  public void setFreeze(Long freeze) {
    this.freeze = freeze;
  }

  public FillOrderInfo dealStock(Long dealStock) {
    this.dealStock = dealStock;
    return this;
  }

   /**
   * Order accumulated deal stock amount
   * @return dealStock
  **/
  @ApiModelProperty(example = "0", value = "Order accumulated deal stock amount")
  public Long getDealStock() {
    return dealStock;
  }

  public void setDealStock(Long dealStock) {
    this.dealStock = dealStock;
  }

  public FillOrderInfo dealMoney(Long dealMoney) {
    this.dealMoney = dealMoney;
    return this;
  }

   /**
   * Order accumulated deal money amount
   * @return dealMoney
  **/
  @ApiModelProperty(example = "0", value = "Order accumulated deal money amount")
  public Long getDealMoney() {
    return dealMoney;
  }

  public void setDealMoney(Long dealMoney) {
    this.dealMoney = dealMoney;
  }

  public FillOrderInfo currStock(Long currStock) {
    this.currStock = currStock;
    return this;
  }

   /**
   * Current block deal stock amount
   * @return currStock
  **/
  @ApiModelProperty(example = "0", value = "Current block deal stock amount")
  public Long getCurrStock() {
    return currStock;
  }

  public void setCurrStock(Long currStock) {
    this.currStock = currStock;
  }

  public FillOrderInfo currMoney(Long currMoney) {
    this.currMoney = currMoney;
    return this;
  }

   /**
   * Current block deal money amount
   * @return currMoney
  **/
  @ApiModelProperty(example = "0", value = "Current block deal money amount")
  public Long getCurrMoney() {
    return currMoney;
  }

  public void setCurrMoney(Long currMoney) {
    this.currMoney = currMoney;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FillOrderInfo fillOrderInfo = (FillOrderInfo) o;
    return Objects.equals(this.orderId, fillOrderInfo.orderId) &&
        Objects.equals(this.tradingPair, fillOrderInfo.tradingPair) &&
        Objects.equals(this.height, fillOrderInfo.height) &&
        Objects.equals(this.side, fillOrderInfo.side) &&
        Objects.equals(this.price, fillOrderInfo.price) &&
        Objects.equals(this.leftStock, fillOrderInfo.leftStock) &&
        Objects.equals(this.freeze, fillOrderInfo.freeze) &&
        Objects.equals(this.dealStock, fillOrderInfo.dealStock) &&
        Objects.equals(this.dealMoney, fillOrderInfo.dealMoney) &&
        Objects.equals(this.currStock, fillOrderInfo.currStock) &&
        Objects.equals(this.currMoney, fillOrderInfo.currMoney);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, tradingPair, height, side, price, leftStock, freeze, dealStock, dealMoney, currStock, currMoney);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FillOrderInfo {\n");
    
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    tradingPair: ").append(toIndentedString(tradingPair)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    side: ").append(toIndentedString(side)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    leftStock: ").append(toIndentedString(leftStock)).append("\n");
    sb.append("    freeze: ").append(toIndentedString(freeze)).append("\n");
    sb.append("    dealStock: ").append(toIndentedString(dealStock)).append("\n");
    sb.append("    dealMoney: ").append(toIndentedString(dealMoney)).append("\n");
    sb.append("    currStock: ").append(toIndentedString(currStock)).append("\n");
    sb.append("    currMoney: ").append(toIndentedString(currMoney)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

