/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.coinex.dex.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;

/**
 * LockedCoin
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-27T01:19:45.029Z")
public class LockedCoin extends HashMap<String, Object> {
  @SerializedName("coin")
  private Coin coin = null;

  @SerializedName("unlock_time")
  private String unlockTime = null;

  @SerializedName("from_address")
  private String fromAddress = null;

  @SerializedName("supervisor")
  private String supervisor = null;

  @SerializedName("reward")
  private String reward = null;

  public LockedCoin coin(Coin coin) {
    this.coin = coin;
    return this;
  }

   /**
   * Get coin
   * @return coin
  **/
  @ApiModelProperty(required = true, value = "")
  public Coin getCoin() {
    return coin;
  }

  public void setCoin(Coin coin) {
    this.coin = coin;
  }

  public LockedCoin unlockTime(String unlockTime) {
    this.unlockTime = unlockTime;
    return this;
  }

   /**
   * Get unlockTime
   * @return unlockTime
  **/
  @ApiModelProperty(example = "1559549834", required = true, value = "")
  public String getUnlockTime() {
    return unlockTime;
  }

  public void setUnlockTime(String unlockTime) {
    this.unlockTime = unlockTime;
  }

  public LockedCoin fromAddress(String fromAddress) {
    this.fromAddress = fromAddress;
    return this;
  }

   /**
   * Get fromAddress
   * @return fromAddress
  **/
  @ApiModelProperty(example = "coinex1y5kdxnzn2tfwayyntf2n28q8q2s80mcul852ke", value = "")
  public String getFromAddress() {
    return fromAddress;
  }

  public void setFromAddress(String fromAddress) {
    this.fromAddress = fromAddress;
  }

  public LockedCoin supervisor(String supervisor) {
    this.supervisor = supervisor;
    return this;
  }

   /**
   * Get supervisor
   * @return supervisor
  **/
  @ApiModelProperty(example = "coinex1dmz7e2fddhejdz5n7e3qc5szx3zn2gj3ta8rwj", value = "")
  public String getSupervisor() {
    return supervisor;
  }

  public void setSupervisor(String supervisor) {
    this.supervisor = supervisor;
  }

  public LockedCoin reward(String reward) {
    this.reward = reward;
    return this;
  }

   /**
   * Get reward
   * @return reward
  **/
  @ApiModelProperty(example = "0", value = "")
  public String getReward() {
    return reward;
  }

  public void setReward(String reward) {
    this.reward = reward;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LockedCoin lockedCoin = (LockedCoin) o;
    return Objects.equals(this.coin, lockedCoin.coin) &&
        Objects.equals(this.unlockTime, lockedCoin.unlockTime) &&
        Objects.equals(this.fromAddress, lockedCoin.fromAddress) &&
        Objects.equals(this.supervisor, lockedCoin.supervisor) &&
        Objects.equals(this.reward, lockedCoin.reward) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coin, unlockTime, fromAddress, supervisor, reward, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LockedCoin {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    coin: ").append(toIndentedString(coin)).append("\n");
    sb.append("    unlockTime: ").append(toIndentedString(unlockTime)).append("\n");
    sb.append("    fromAddress: ").append(toIndentedString(fromAddress)).append("\n");
    sb.append("    supervisor: ").append(toIndentedString(supervisor)).append("\n");
    sb.append("    reward: ").append(toIndentedString(reward)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

