/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.coinex.dex.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.coinex.dex.client.model.BaseReq;
import org.coinex.dex.client.model.Coin;
import org.coinex.dex.client.model.ParamChange;

/**
 * PostProposalBody1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-09T11:28:51.986+08:00")
public class PostProposalBody1 {
  @SerializedName("base_req")
  private BaseReq baseReq = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("proposal_type")
  private String proposalType = null;

  @SerializedName("proposer")
  private String proposer = null;

  @SerializedName("deposit")
  private List<Coin> deposit = new ArrayList<>();

  @SerializedName("changes")
  private List<ParamChange> changes = new ArrayList<>();

  public PostProposalBody1 baseReq(BaseReq baseReq) {
    this.baseReq = baseReq;
    return this;
  }

   /**
   * Get baseReq
   * @return baseReq
  **/
  @ApiModelProperty(required = true, value = "")
  public BaseReq getBaseReq() {
    return baseReq;
  }

  public void setBaseReq(BaseReq baseReq) {
    this.baseReq = baseReq;
  }

  public PostProposalBody1 title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public PostProposalBody1 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public PostProposalBody1 proposalType(String proposalType) {
    this.proposalType = proposalType;
    return this;
  }

   /**
   * Get proposalType
   * @return proposalType
  **/
  @ApiModelProperty(example = "text", required = true, value = "")
  public String getProposalType() {
    return proposalType;
  }

  public void setProposalType(String proposalType) {
    this.proposalType = proposalType;
  }

  public PostProposalBody1 proposer(String proposer) {
    this.proposer = proposer;
    return this;
  }

   /**
   * Get proposer
   * @return proposer
  **/
  @ApiModelProperty(required = true, value = "")
  public String getProposer() {
    return proposer;
  }

  public void setProposer(String proposer) {
    this.proposer = proposer;
  }

  public PostProposalBody1 deposit(List<Coin> deposit) {
    this.deposit = deposit;
    return this;
  }

  public PostProposalBody1 addDepositItem(Coin depositItem) {
    this.deposit.add(depositItem);
    return this;
  }

   /**
   * Get deposit
   * @return deposit
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Coin> getDeposit() {
    return deposit;
  }

  public void setDeposit(List<Coin> deposit) {
    this.deposit = deposit;
  }

  public PostProposalBody1 changes(List<ParamChange> changes) {
    this.changes = changes;
    return this;
  }

  public PostProposalBody1 addChangesItem(ParamChange changesItem) {
    this.changes.add(changesItem);
    return this;
  }

   /**
   * Get changes
   * @return changes
  **/
  @ApiModelProperty(required = true, value = "")
  public List<ParamChange> getChanges() {
    return changes;
  }

  public void setChanges(List<ParamChange> changes) {
    this.changes = changes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostProposalBody1 postProposalBody1 = (PostProposalBody1) o;
    return Objects.equals(this.baseReq, postProposalBody1.baseReq) &&
        Objects.equals(this.title, postProposalBody1.title) &&
        Objects.equals(this.description, postProposalBody1.description) &&
        Objects.equals(this.proposalType, postProposalBody1.proposalType) &&
        Objects.equals(this.proposer, postProposalBody1.proposer) &&
        Objects.equals(this.deposit, postProposalBody1.deposit) &&
        Objects.equals(this.changes, postProposalBody1.changes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baseReq, title, description, proposalType, proposer, deposit, changes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostProposalBody1 {\n");
    
    sb.append("    baseReq: ").append(toIndentedString(baseReq)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    proposalType: ").append(toIndentedString(proposalType)).append("\n");
    sb.append("    proposer: ").append(toIndentedString(proposer)).append("\n");
    sb.append("    deposit: ").append(toIndentedString(deposit)).append("\n");
    sb.append("    changes: ").append(toIndentedString(changes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

