/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.coinex.dex.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.coinex.dex.client.model.BaseReq;
import org.coinex.dex.client.model.Coin;

/**
 * PostProposalBody2
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-28T12:10:24.313+08:00")
public class PostProposalBody2 {
  @SerializedName("base_req")
  private BaseReq baseReq = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("proposer")
  private String proposer = null;

  @SerializedName("recipient")
  private String recipient = null;

  @SerializedName("deposit")
  private List<Coin> deposit = new ArrayList<>();

  @SerializedName("amount")
  private List<Coin> amount = new ArrayList<>();

  public PostProposalBody2 baseReq(BaseReq baseReq) {
    this.baseReq = baseReq;
    return this;
  }

   /**
   * Get baseReq
   * @return baseReq
  **/
  @ApiModelProperty(required = true, value = "")
  public BaseReq getBaseReq() {
    return baseReq;
  }

  public void setBaseReq(BaseReq baseReq) {
    this.baseReq = baseReq;
  }

  public PostProposalBody2 title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public PostProposalBody2 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public PostProposalBody2 proposer(String proposer) {
    this.proposer = proposer;
    return this;
  }

   /**
   * Get proposer
   * @return proposer
  **/
  @ApiModelProperty(required = true, value = "")
  public String getProposer() {
    return proposer;
  }

  public void setProposer(String proposer) {
    this.proposer = proposer;
  }

  public PostProposalBody2 recipient(String recipient) {
    this.recipient = recipient;
    return this;
  }

   /**
   * Get recipient
   * @return recipient
  **/
  @ApiModelProperty(required = true, value = "")
  public String getRecipient() {
    return recipient;
  }

  public void setRecipient(String recipient) {
    this.recipient = recipient;
  }

  public PostProposalBody2 deposit(List<Coin> deposit) {
    this.deposit = deposit;
    return this;
  }

  public PostProposalBody2 addDepositItem(Coin depositItem) {
    this.deposit.add(depositItem);
    return this;
  }

   /**
   * Get deposit
   * @return deposit
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Coin> getDeposit() {
    return deposit;
  }

  public void setDeposit(List<Coin> deposit) {
    this.deposit = deposit;
  }

  public PostProposalBody2 amount(List<Coin> amount) {
    this.amount = amount;
    return this;
  }

  public PostProposalBody2 addAmountItem(Coin amountItem) {
    this.amount.add(amountItem);
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Coin> getAmount() {
    return amount;
  }

  public void setAmount(List<Coin> amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostProposalBody2 postProposalBody2 = (PostProposalBody2) o;
    return Objects.equals(this.baseReq, postProposalBody2.baseReq) &&
        Objects.equals(this.title, postProposalBody2.title) &&
        Objects.equals(this.description, postProposalBody2.description) &&
        Objects.equals(this.proposer, postProposalBody2.proposer) &&
        Objects.equals(this.recipient, postProposalBody2.recipient) &&
        Objects.equals(this.deposit, postProposalBody2.deposit) &&
        Objects.equals(this.amount, postProposalBody2.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baseReq, title, description, proposer, recipient, deposit, amount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostProposalBody2 {\n");
    
    sb.append("    baseReq: ").append(toIndentedString(baseReq)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    proposer: ").append(toIndentedString(proposer)).append("\n");
    sb.append("    recipient: ").append(toIndentedString(recipient)).append("\n");
    sb.append("    deposit: ").append(toIndentedString(deposit)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

