/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.coinex.dex.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.coinex.dex.client.model.RedelegationEntry;

/**
 * Redelegation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-09T11:28:51.986+08:00")
public class Redelegation {
  @SerializedName("delegator_address")
  private String delegatorAddress = null;

  @SerializedName("validator_src_address")
  private String validatorSrcAddress = null;

  @SerializedName("validator_dst_address")
  private String validatorDstAddress = null;

  @SerializedName("entries")
  private List<RedelegationEntry> entries = new ArrayList<>();

  public Redelegation delegatorAddress(String delegatorAddress) {
    this.delegatorAddress = delegatorAddress;
    return this;
  }

   /**
   * Get delegatorAddress
   * @return delegatorAddress
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDelegatorAddress() {
    return delegatorAddress;
  }

  public void setDelegatorAddress(String delegatorAddress) {
    this.delegatorAddress = delegatorAddress;
  }

  public Redelegation validatorSrcAddress(String validatorSrcAddress) {
    this.validatorSrcAddress = validatorSrcAddress;
    return this;
  }

   /**
   * Get validatorSrcAddress
   * @return validatorSrcAddress
  **/
  @ApiModelProperty(required = true, value = "")
  public String getValidatorSrcAddress() {
    return validatorSrcAddress;
  }

  public void setValidatorSrcAddress(String validatorSrcAddress) {
    this.validatorSrcAddress = validatorSrcAddress;
  }

  public Redelegation validatorDstAddress(String validatorDstAddress) {
    this.validatorDstAddress = validatorDstAddress;
    return this;
  }

   /**
   * Get validatorDstAddress
   * @return validatorDstAddress
  **/
  @ApiModelProperty(required = true, value = "")
  public String getValidatorDstAddress() {
    return validatorDstAddress;
  }

  public void setValidatorDstAddress(String validatorDstAddress) {
    this.validatorDstAddress = validatorDstAddress;
  }

  public Redelegation entries(List<RedelegationEntry> entries) {
    this.entries = entries;
    return this;
  }

  public Redelegation addEntriesItem(RedelegationEntry entriesItem) {
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  @ApiModelProperty(required = true, value = "")
  public List<RedelegationEntry> getEntries() {
    return entries;
  }

  public void setEntries(List<RedelegationEntry> entries) {
    this.entries = entries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Redelegation redelegation = (Redelegation) o;
    return Objects.equals(this.delegatorAddress, redelegation.delegatorAddress) &&
        Objects.equals(this.validatorSrcAddress, redelegation.validatorSrcAddress) &&
        Objects.equals(this.validatorDstAddress, redelegation.validatorDstAddress) &&
        Objects.equals(this.entries, redelegation.entries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(delegatorAddress, validatorSrcAddress, validatorDstAddress, entries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Redelegation {\n");
    
    sb.append("    delegatorAddress: ").append(toIndentedString(delegatorAddress)).append("\n");
    sb.append("    validatorSrcAddress: ").append(toIndentedString(validatorSrcAddress)).append("\n");
    sb.append("    validatorDstAddress: ").append(toIndentedString(validatorDstAddress)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

