/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.coinex.dex.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;

/**
 * RedelegationEntry
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-27T01:19:45.029Z")
public class RedelegationEntry extends HashMap<String, Object> {
  @SerializedName("creation_height")
  private Integer creationHeight = null;

  @SerializedName("completion_time")
  private String completionTime = null;

  @SerializedName("initial_balance")
  private String initialBalance = null;

  @SerializedName("shares_dst")
  private String sharesDst = null;

  @SerializedName("balance")
  private String balance = null;

  public RedelegationEntry creationHeight(Integer creationHeight) {
    this.creationHeight = creationHeight;
    return this;
  }

   /**
   * Get creationHeight
   * @return creationHeight
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getCreationHeight() {
    return creationHeight;
  }

  public void setCreationHeight(Integer creationHeight) {
    this.creationHeight = creationHeight;
  }

  public RedelegationEntry completionTime(String completionTime) {
    this.completionTime = completionTime;
    return this;
  }

   /**
   * Get completionTime
   * @return completionTime
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCompletionTime() {
    return completionTime;
  }

  public void setCompletionTime(String completionTime) {
    this.completionTime = completionTime;
  }

  public RedelegationEntry initialBalance(String initialBalance) {
    this.initialBalance = initialBalance;
    return this;
  }

   /**
   * Get initialBalance
   * @return initialBalance
  **/
  @ApiModelProperty(required = true, value = "")
  public String getInitialBalance() {
    return initialBalance;
  }

  public void setInitialBalance(String initialBalance) {
    this.initialBalance = initialBalance;
  }

  public RedelegationEntry sharesDst(String sharesDst) {
    this.sharesDst = sharesDst;
    return this;
  }

   /**
   * Get sharesDst
   * @return sharesDst
  **/
  @ApiModelProperty(required = true, value = "")
  public String getSharesDst() {
    return sharesDst;
  }

  public void setSharesDst(String sharesDst) {
    this.sharesDst = sharesDst;
  }

  public RedelegationEntry balance(String balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Get balance
   * @return balance
  **/
  @ApiModelProperty(required = true, value = "")
  public String getBalance() {
    return balance;
  }

  public void setBalance(String balance) {
    this.balance = balance;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RedelegationEntry redelegationEntry = (RedelegationEntry) o;
    return Objects.equals(this.creationHeight, redelegationEntry.creationHeight) &&
        Objects.equals(this.completionTime, redelegationEntry.completionTime) &&
        Objects.equals(this.initialBalance, redelegationEntry.initialBalance) &&
        Objects.equals(this.sharesDst, redelegationEntry.sharesDst) &&
        Objects.equals(this.balance, redelegationEntry.balance) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationHeight, completionTime, initialBalance, sharesDst, balance, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RedelegationEntry {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    creationHeight: ").append(toIndentedString(creationHeight)).append("\n");
    sb.append("    completionTime: ").append(toIndentedString(completionTime)).append("\n");
    sb.append("    initialBalance: ").append(toIndentedString(initialBalance)).append("\n");
    sb.append("    sharesDst: ").append(toIndentedString(sharesDst)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

