/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.coinex.dex.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.coinex.dex.client.model.Coin;
import org.coinex.dex.client.model.LockedCoin;

/**
 * Unlock
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-09T11:28:51.986+08:00")
public class Unlock {
  @SerializedName("address")
  private String address = null;

  @SerializedName("unlocked")
  private List<Coin> unlocked = null;

  @SerializedName("locked_coins")
  private List<LockedCoin> lockedCoins = null;

  @SerializedName("frozen_coins")
  private List<Coin> frozenCoins = null;

  @SerializedName("coins")
  private List<Coin> coins = null;

  @SerializedName("height")
  private Long height = null;

  public Unlock address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public Unlock unlocked(List<Coin> unlocked) {
    this.unlocked = unlocked;
    return this;
  }

  public Unlock addUnlockedItem(Coin unlockedItem) {
    if (this.unlocked == null) {
      this.unlocked = new ArrayList<>();
    }
    this.unlocked.add(unlockedItem);
    return this;
  }

   /**
   * Get unlocked
   * @return unlocked
  **/
  @ApiModelProperty(value = "")
  public List<Coin> getUnlocked() {
    return unlocked;
  }

  public void setUnlocked(List<Coin> unlocked) {
    this.unlocked = unlocked;
  }

  public Unlock lockedCoins(List<LockedCoin> lockedCoins) {
    this.lockedCoins = lockedCoins;
    return this;
  }

  public Unlock addLockedCoinsItem(LockedCoin lockedCoinsItem) {
    if (this.lockedCoins == null) {
      this.lockedCoins = new ArrayList<>();
    }
    this.lockedCoins.add(lockedCoinsItem);
    return this;
  }

   /**
   * Get lockedCoins
   * @return lockedCoins
  **/
  @ApiModelProperty(value = "")
  public List<LockedCoin> getLockedCoins() {
    return lockedCoins;
  }

  public void setLockedCoins(List<LockedCoin> lockedCoins) {
    this.lockedCoins = lockedCoins;
  }

  public Unlock frozenCoins(List<Coin> frozenCoins) {
    this.frozenCoins = frozenCoins;
    return this;
  }

  public Unlock addFrozenCoinsItem(Coin frozenCoinsItem) {
    if (this.frozenCoins == null) {
      this.frozenCoins = new ArrayList<>();
    }
    this.frozenCoins.add(frozenCoinsItem);
    return this;
  }

   /**
   * Get frozenCoins
   * @return frozenCoins
  **/
  @ApiModelProperty(value = "")
  public List<Coin> getFrozenCoins() {
    return frozenCoins;
  }

  public void setFrozenCoins(List<Coin> frozenCoins) {
    this.frozenCoins = frozenCoins;
  }

  public Unlock coins(List<Coin> coins) {
    this.coins = coins;
    return this;
  }

  public Unlock addCoinsItem(Coin coinsItem) {
    if (this.coins == null) {
      this.coins = new ArrayList<>();
    }
    this.coins.add(coinsItem);
    return this;
  }

   /**
   * Get coins
   * @return coins
  **/
  @ApiModelProperty(value = "")
  public List<Coin> getCoins() {
    return coins;
  }

  public void setCoins(List<Coin> coins) {
    this.coins = coins;
  }

  public Unlock height(Long height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @ApiModelProperty(example = "0", value = "")
  public Long getHeight() {
    return height;
  }

  public void setHeight(Long height) {
    this.height = height;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Unlock unlock = (Unlock) o;
    return Objects.equals(this.address, unlock.address) &&
        Objects.equals(this.unlocked, unlock.unlocked) &&
        Objects.equals(this.lockedCoins, unlock.lockedCoins) &&
        Objects.equals(this.frozenCoins, unlock.frozenCoins) &&
        Objects.equals(this.coins, unlock.coins) &&
        Objects.equals(this.height, unlock.height);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, unlocked, lockedCoins, frozenCoins, coins, height);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Unlock {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    unlocked: ").append(toIndentedString(unlocked)).append("\n");
    sb.append("    lockedCoins: ").append(toIndentedString(lockedCoins)).append("\n");
    sb.append("    frozenCoins: ").append(toIndentedString(frozenCoins)).append("\n");
    sb.append("    coins: ").append(toIndentedString(coins)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

