/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.coinex.dex.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.coinex.dex.client.model.InlineResponse20056;
import org.coinex.dex.client.model.UserOrderCancelOrderInfo;
import org.coinex.dex.client.model.UserOrderCreateOrderInfo;

/**
 * UserOrder
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-09T11:28:51.986+08:00")
public class UserOrder {
  @SerializedName("createOrderInfo")
  private UserOrderCreateOrderInfo createOrderInfo = null;

  @SerializedName("fillOrderInfo")
  private InlineResponse20056 fillOrderInfo = null;

  @SerializedName("cancelOrderInfo")
  private UserOrderCancelOrderInfo cancelOrderInfo = null;

  public UserOrder createOrderInfo(UserOrderCreateOrderInfo createOrderInfo) {
    this.createOrderInfo = createOrderInfo;
    return this;
  }

   /**
   * Get createOrderInfo
   * @return createOrderInfo
  **/
  @ApiModelProperty(value = "")
  public UserOrderCreateOrderInfo getCreateOrderInfo() {
    return createOrderInfo;
  }

  public void setCreateOrderInfo(UserOrderCreateOrderInfo createOrderInfo) {
    this.createOrderInfo = createOrderInfo;
  }

  public UserOrder fillOrderInfo(InlineResponse20056 fillOrderInfo) {
    this.fillOrderInfo = fillOrderInfo;
    return this;
  }

   /**
   * Get fillOrderInfo
   * @return fillOrderInfo
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20056 getFillOrderInfo() {
    return fillOrderInfo;
  }

  public void setFillOrderInfo(InlineResponse20056 fillOrderInfo) {
    this.fillOrderInfo = fillOrderInfo;
  }

  public UserOrder cancelOrderInfo(UserOrderCancelOrderInfo cancelOrderInfo) {
    this.cancelOrderInfo = cancelOrderInfo;
    return this;
  }

   /**
   * Get cancelOrderInfo
   * @return cancelOrderInfo
  **/
  @ApiModelProperty(value = "")
  public UserOrderCancelOrderInfo getCancelOrderInfo() {
    return cancelOrderInfo;
  }

  public void setCancelOrderInfo(UserOrderCancelOrderInfo cancelOrderInfo) {
    this.cancelOrderInfo = cancelOrderInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserOrder userOrder = (UserOrder) o;
    return Objects.equals(this.createOrderInfo, userOrder.createOrderInfo) &&
        Objects.equals(this.fillOrderInfo, userOrder.fillOrderInfo) &&
        Objects.equals(this.cancelOrderInfo, userOrder.cancelOrderInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createOrderInfo, fillOrderInfo, cancelOrderInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserOrder {\n");
    
    sb.append("    createOrderInfo: ").append(toIndentedString(createOrderInfo)).append("\n");
    sb.append("    fillOrderInfo: ").append(toIndentedString(fillOrderInfo)).append("\n");
    sb.append("    cancelOrderInfo: ").append(toIndentedString(cancelOrderInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

