/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.coinex.dex.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.coinex.dex.client.model.ValidatorCommissionCommissionRates;

/**
 * ValidatorCommission
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-28T12:10:24.313+08:00")
public class ValidatorCommission {
  @SerializedName("commission_rates")
  private ValidatorCommissionCommissionRates commissionRates = null;

  @SerializedName("update_time")
  private String updateTime = null;

  public ValidatorCommission commissionRates(ValidatorCommissionCommissionRates commissionRates) {
    this.commissionRates = commissionRates;
    return this;
  }

   /**
   * Get commissionRates
   * @return commissionRates
  **/
  @ApiModelProperty(required = true, value = "")
  public ValidatorCommissionCommissionRates getCommissionRates() {
    return commissionRates;
  }

  public void setCommissionRates(ValidatorCommissionCommissionRates commissionRates) {
    this.commissionRates = commissionRates;
  }

  public ValidatorCommission updateTime(String updateTime) {
    this.updateTime = updateTime;
    return this;
  }

   /**
   * Get updateTime
   * @return updateTime
  **/
  @ApiModelProperty(example = "1970-01-01T00:00:00Z", required = true, value = "")
  public String getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidatorCommission validatorCommission = (ValidatorCommission) o;
    return Objects.equals(this.commissionRates, validatorCommission.commissionRates) &&
        Objects.equals(this.updateTime, validatorCommission.updateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commissionRates, updateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidatorCommission {\n");
    
    sb.append("    commissionRates: ").append(toIndentedString(commissionRates)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

