/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BaseReq;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * BancorTrade
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-27T01:19:45.029Z")
public class BancorTrade extends HashMap<String, Object> {
  @SerializedName("base_req")
  private BaseReq baseReq = null;

  @SerializedName("stock")
  private String stock = null;

  @SerializedName("money")
  private String money = null;

  @SerializedName("amount")
  private String amount = null;

  @SerializedName("is_buy")
  private Boolean isBuy = null;

  @SerializedName("money_limit")
  private String moneyLimit = null;

  public BancorTrade baseReq(BaseReq baseReq) {
    this.baseReq = baseReq;
    return this;
  }

   /**
   * Get baseReq
   * @return baseReq
  **/
  @ApiModelProperty(required = true, value = "")
  public BaseReq getBaseReq() {
    return baseReq;
  }

  public void setBaseReq(BaseReq baseReq) {
    this.baseReq = baseReq;
  }

  public BancorTrade stock(String stock) {
    this.stock = stock;
    return this;
  }

   /**
   * Get stock
   * @return stock
  **/
  @ApiModelProperty(example = "btc", required = true, value = "")
  public String getStock() {
    return stock;
  }

  public void setStock(String stock) {
    this.stock = stock;
  }

  public BancorTrade money(String money) {
    this.money = money;
    return this;
  }

   /**
   * Get money
   * @return money
  **/
  @ApiModelProperty(example = "cet", required = true, value = "")
  public String getMoney() {
    return money;
  }

  public void setMoney(String money) {
    this.money = money;
  }

  public BancorTrade amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(example = "100", required = true, value = "")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public BancorTrade isBuy(Boolean isBuy) {
    this.isBuy = isBuy;
    return this;
  }

   /**
   * Get isBuy
   * @return isBuy
  **/
  @ApiModelProperty(example = "true", required = true, value = "")
  public Boolean isIsBuy() {
    return isBuy;
  }

  public void setIsBuy(Boolean isBuy) {
    this.isBuy = isBuy;
  }

  public BancorTrade moneyLimit(String moneyLimit) {
    this.moneyLimit = moneyLimit;
    return this;
  }

   /**
   * Get moneyLimit
   * @return moneyLimit
  **/
  @ApiModelProperty(example = "1000", required = true, value = "")
  public String getMoneyLimit() {
    return moneyLimit;
  }

  public void setMoneyLimit(String moneyLimit) {
    this.moneyLimit = moneyLimit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BancorTrade bancorTrade = (BancorTrade) o;
    return Objects.equals(this.baseReq, bancorTrade.baseReq) &&
        Objects.equals(this.stock, bancorTrade.stock) &&
        Objects.equals(this.money, bancorTrade.money) &&
        Objects.equals(this.amount, bancorTrade.amount) &&
        Objects.equals(this.isBuy, bancorTrade.isBuy) &&
        Objects.equals(this.moneyLimit, bancorTrade.moneyLimit) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baseReq, stock, money, amount, isBuy, moneyLimit, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BancorTrade {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    baseReq: ").append(toIndentedString(baseReq)).append("\n");
    sb.append("    stock: ").append(toIndentedString(stock)).append("\n");
    sb.append("    money: ").append(toIndentedString(money)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    isBuy: ").append(toIndentedString(isBuy)).append("\n");
    sb.append("    moneyLimit: ").append(toIndentedString(moneyLimit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

