/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Coin;
import io.swagger.client.model.DelegationDelegatorReward;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * DelegatorTotalRewards
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-27T01:19:45.029Z")
public class DelegatorTotalRewards extends HashMap<String, Object> {
  @SerializedName("rewards")
  private List<DelegationDelegatorReward> rewards = new ArrayList<DelegationDelegatorReward>();

  @SerializedName("total")
  private List<Coin> total = new ArrayList<Coin>();

  public DelegatorTotalRewards rewards(List<DelegationDelegatorReward> rewards) {
    this.rewards = rewards;
    return this;
  }

  public DelegatorTotalRewards addRewardsItem(DelegationDelegatorReward rewardsItem) {
    this.rewards.add(rewardsItem);
    return this;
  }

   /**
   * Get rewards
   * @return rewards
  **/
  @ApiModelProperty(required = true, value = "")
  public List<DelegationDelegatorReward> getRewards() {
    return rewards;
  }

  public void setRewards(List<DelegationDelegatorReward> rewards) {
    this.rewards = rewards;
  }

  public DelegatorTotalRewards total(List<Coin> total) {
    this.total = total;
    return this;
  }

  public DelegatorTotalRewards addTotalItem(Coin totalItem) {
    this.total.add(totalItem);
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Coin> getTotal() {
    return total;
  }

  public void setTotal(List<Coin> total) {
    this.total = total;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DelegatorTotalRewards delegatorTotalRewards = (DelegatorTotalRewards) o;
    return Objects.equals(this.rewards, delegatorTotalRewards.rewards) &&
        Objects.equals(this.total, delegatorTotalRewards.total) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rewards, total, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DelegatorTotalRewards {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    rewards: ").append(toIndentedString(rewards)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

