/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse20036ResultPlans;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20036Result
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-27T01:19:45.029Z")
public class InlineResponse20036Result {
  @SerializedName("default_reward_per_block")
  private String defaultRewardPerBlock = null;

  @SerializedName("plans")
  private List<InlineResponse20036ResultPlans> plans = null;

  public InlineResponse20036Result defaultRewardPerBlock(String defaultRewardPerBlock) {
    this.defaultRewardPerBlock = defaultRewardPerBlock;
    return this;
  }

   /**
   * Get defaultRewardPerBlock
   * @return defaultRewardPerBlock
  **/
  @ApiModelProperty(value = "")
  public String getDefaultRewardPerBlock() {
    return defaultRewardPerBlock;
  }

  public void setDefaultRewardPerBlock(String defaultRewardPerBlock) {
    this.defaultRewardPerBlock = defaultRewardPerBlock;
  }

  public InlineResponse20036Result plans(List<InlineResponse20036ResultPlans> plans) {
    this.plans = plans;
    return this;
  }

  public InlineResponse20036Result addPlansItem(InlineResponse20036ResultPlans plansItem) {
    if (this.plans == null) {
      this.plans = new ArrayList<InlineResponse20036ResultPlans>();
    }
    this.plans.add(plansItem);
    return this;
  }

   /**
   * Get plans
   * @return plans
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20036ResultPlans> getPlans() {
    return plans;
  }

  public void setPlans(List<InlineResponse20036ResultPlans> plans) {
    this.plans = plans;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20036Result inlineResponse20036Result = (InlineResponse20036Result) o;
    return Objects.equals(this.defaultRewardPerBlock, inlineResponse20036Result.defaultRewardPerBlock) &&
        Objects.equals(this.plans, inlineResponse20036Result.plans);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultRewardPerBlock, plans);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20036Result {\n");
    
    sb.append("    defaultRewardPerBlock: ").append(toIndentedString(defaultRewardPerBlock)).append("\n");
    sb.append("    plans: ").append(toIndentedString(plans)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

