/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * TallyResult
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-26T10:53:15.911+08:00[Asia/Shanghai]")
public class TallyResult {
  @SerializedName("yes")
  private String yes = null;

  @SerializedName("abstain")
  private String abstain = null;

  @SerializedName("no")
  private String no = null;

  @SerializedName("no_with_veto")
  private String noWithVeto = null;

  public TallyResult yes(String yes) {
    this.yes = yes;
    return this;
  }

   /**
   * Get yes
   * @return yes
  **/
  @Schema(example = "0.0000000000", required = true, description = "")
  public String getYes() {
    return yes;
  }

  public void setYes(String yes) {
    this.yes = yes;
  }

  public TallyResult abstain(String abstain) {
    this.abstain = abstain;
    return this;
  }

   /**
   * Get abstain
   * @return abstain
  **/
  @Schema(example = "0.0000000000", required = true, description = "")
  public String getAbstain() {
    return abstain;
  }

  public void setAbstain(String abstain) {
    this.abstain = abstain;
  }

  public TallyResult no(String no) {
    this.no = no;
    return this;
  }

   /**
   * Get no
   * @return no
  **/
  @Schema(example = "0.0000000000", required = true, description = "")
  public String getNo() {
    return no;
  }

  public void setNo(String no) {
    this.no = no;
  }

  public TallyResult noWithVeto(String noWithVeto) {
    this.noWithVeto = noWithVeto;
    return this;
  }

   /**
   * Get noWithVeto
   * @return noWithVeto
  **/
  @Schema(example = "0.0000000000", required = true, description = "")
  public String getNoWithVeto() {
    return noWithVeto;
  }

  public void setNoWithVeto(String noWithVeto) {
    this.noWithVeto = noWithVeto;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TallyResult tallyResult = (TallyResult) o;
    return Objects.equals(this.yes, tallyResult.yes) &&
        Objects.equals(this.abstain, tallyResult.abstain) &&
        Objects.equals(this.no, tallyResult.no) &&
        Objects.equals(this.noWithVeto, tallyResult.noWithVeto);
  }

  @Override
  public int hashCode() {
    return Objects.hash(yes, abstain, no, noWithVeto);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TallyResult {\n");
    
    sb.append("    yes: ").append(toIndentedString(yes)).append("\n");
    sb.append("    abstain: ").append(toIndentedString(abstain)).append("\n");
    sb.append("    no: ").append(toIndentedString(no)).append("\n");
    sb.append("    noWithVeto: ").append(toIndentedString(noWithVeto)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
