/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.UnbondingEntries;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * UnbondingDelegationPair
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-27T01:19:45.029Z")
public class UnbondingDelegationPair extends HashMap<String, Object> {
  @SerializedName("delegator_address")
  private String delegatorAddress = null;

  @SerializedName("validator_address")
  private String validatorAddress = null;

  @SerializedName("entries")
  private List<UnbondingEntries> entries = new ArrayList<UnbondingEntries>();

  public UnbondingDelegationPair delegatorAddress(String delegatorAddress) {
    this.delegatorAddress = delegatorAddress;
    return this;
  }

   /**
   * Get delegatorAddress
   * @return delegatorAddress
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDelegatorAddress() {
    return delegatorAddress;
  }

  public void setDelegatorAddress(String delegatorAddress) {
    this.delegatorAddress = delegatorAddress;
  }

  public UnbondingDelegationPair validatorAddress(String validatorAddress) {
    this.validatorAddress = validatorAddress;
    return this;
  }

   /**
   * Get validatorAddress
   * @return validatorAddress
  **/
  @ApiModelProperty(required = true, value = "")
  public String getValidatorAddress() {
    return validatorAddress;
  }

  public void setValidatorAddress(String validatorAddress) {
    this.validatorAddress = validatorAddress;
  }

  public UnbondingDelegationPair entries(List<UnbondingEntries> entries) {
    this.entries = entries;
    return this;
  }

  public UnbondingDelegationPair addEntriesItem(UnbondingEntries entriesItem) {
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  @ApiModelProperty(required = true, value = "")
  public List<UnbondingEntries> getEntries() {
    return entries;
  }

  public void setEntries(List<UnbondingEntries> entries) {
    this.entries = entries;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnbondingDelegationPair unbondingDelegationPair = (UnbondingDelegationPair) o;
    return Objects.equals(this.delegatorAddress, unbondingDelegationPair.delegatorAddress) &&
        Objects.equals(this.validatorAddress, unbondingDelegationPair.validatorAddress) &&
        Objects.equals(this.entries, unbondingDelegationPair.entries) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(delegatorAddress, validatorAddress, entries, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnbondingDelegationPair {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    delegatorAddress: ").append(toIndentedString(delegatorAddress)).append("\n");
    sb.append("    validatorAddress: ").append(toIndentedString(validatorAddress)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

