/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.StdTx;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AliasApi
 */
@Ignore
public class AliasApiTest {

    private final AliasApi api = new AliasApi();

    /**
     * Given an alias, query the corresponding address
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAddressFromAliasTest() throws ApiException {
        String alias = null;
        Object response = api.getAddressFromAlias(alias);

        // TODO: test validations
    }
    /**
     * Get the current alias parameters
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAliasParamsTest() throws ApiException {
        Object response = api.getAliasParams();

        // TODO: test validations
    }
    /**
     * Given an account&#x27;s address, query all the corresponding aliases
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAliasesFromAddressTest() throws ApiException {
        String address = null;
        Object response = api.getAliasesFromAddress(address);

        // TODO: test validations
    }
    /**
     * Add or remove alias for an address
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateAliasTest() throws ApiException {
        Object body = null;
        StdTx response = api.updateAlias(body);

        // TODO: test validations
    }
}
