/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Addresses;
import io.swagger.client.model.IssueToken;
import io.swagger.client.model.StdTx;
import io.swagger.client.model.Whitelist;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AssetApi
 */
@Ignore
public class AssetApiTest {

    private final AssetApi api = new AssetApi();

    /**
     * Add forbid whitelist
     *
     * Add forbiddable token whitelist addr
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addWhitelistTest() throws ApiException {
        Whitelist body = null;
        String symbol = null;
        StdTx response = api.addWhitelist(body, symbol);

        // TODO: test validations
    }
    /**
     * Burn token
     *
     * Burn burnable token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void burnTokenTest() throws ApiException {
        Object body = null;
        String symbol = null;
        StdTx response = api.burnToken(body, symbol);

        // TODO: test validations
    }
    /**
     * Forbid address
     *
     * Add forbidden addresses
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void forbidAddrTest() throws ApiException {
        Addresses body = null;
        String symbol = null;
        StdTx response = api.forbidAddr(body, symbol);

        // TODO: test validations
    }
    /**
     * Forbid token
     *
     * Forbid forbiddable token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void forbidTokenTest() throws ApiException {
        Object body = null;
        String symbol = null;
        StdTx response = api.forbidToken(body, symbol);

        // TODO: test validations
    }
    /**
     * Get the current asset parameters
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAssetParamsTest() throws ApiException {
        Object response = api.getAssetParams();

        // TODO: test validations
    }
    /**
     * query forbidden addresses
     *
     * Get forbidden addresses with provided &#x60;symbol&#x60;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getForbiddenAddressesTest() throws ApiException {
        String symbol = null;
        Object response = api.getForbiddenAddresses(symbol);

        // TODO: test validations
    }
    /**
     * List reserved symbols
     *
     * List all reserved symbols
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getReservedSymbolsTest() throws ApiException {
        Object response = api.getReservedSymbols();

        // TODO: test validations
    }
    /**
     * queryToken
     *
     * Get token with provided &#x60;symbol&#x60;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTokenTest() throws ApiException {
        String symbol = null;
        Object response = api.getToken(symbol);

        // TODO: test validations
    }
    /**
     * List tokens
     *
     * List all existing tokens
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTokenListTest() throws ApiException {
        Object response = api.getTokenList();

        // TODO: test validations
    }
    /**
     * queryWhitelist
     *
     * Get token whitelist with provided &#x60;symbol&#x60;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWhitelistTest() throws ApiException {
        String symbol = null;
        Object response = api.getWhitelist(symbol);

        // TODO: test validations
    }
    /**
     * Issue token
     *
     * Issue a new Token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void issueTokenTest() throws ApiException {
        IssueToken body = null;
        StdTx response = api.issueToken(body);

        // TODO: test validations
    }
    /**
     * Mint token
     *
     * Mint mintable token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void mintTokenTest() throws ApiException {
        Object body = null;
        String symbol = null;
        StdTx response = api.mintToken(body, symbol);

        // TODO: test validations
    }
    /**
     * Modify token info
     *
     * Modify token info
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void modifyTokenInfoTest() throws ApiException {
        Object body = null;
        String symbol = null;
        StdTx response = api.modifyTokenInfo(body, symbol);

        // TODO: test validations
    }
    /**
     * Remove forbid whitelist
     *
     * Remove forbiddable token whitelist addr
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeWhitelistTest() throws ApiException {
        Whitelist body = null;
        String symbol = null;
        StdTx response = api.removeWhitelist(body, symbol);

        // TODO: test validations
    }
    /**
     * Transfer ownership
     *
     * Transfer token owner ship
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transferOwnershipTest() throws ApiException {
        Object body = null;
        String symbol = null;
        StdTx response = api.transferOwnership(body, symbol);

        // TODO: test validations
    }
    /**
     * UnForbid address
     *
     * Remove forbidden addresses
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void unForbidAddrTest() throws ApiException {
        Addresses body = null;
        String symbol = null;
        StdTx response = api.unForbidAddr(body, symbol);

        // TODO: test validations
    }
    /**
     * UnForbid token
     *
     * UnForbid forbiddable token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void unFrobidTokenTest() throws ApiException {
        Object body = null;
        String symbol = null;
        StdTx response = api.unFrobidToken(body, symbol);

        // TODO: test validations
    }
}
