/*
 * CET-Lite for CoinEx Chain
 * A REST interface for state queries, transaction generation and broadcasting.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.FollowupCommentReq;
import io.swagger.client.model.NewThreadReq;
import io.swagger.client.model.RewardCommentsReq;
import io.swagger.client.model.StdTx;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CommentApi
 */
@Ignore
public class CommentApiTest {

    private final CommentApi api = new CommentApi();

    
    /**
     * Post a follow-up comment under some thread
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void followupCommentTest() throws ApiException {
        FollowupCommentReq followupCommentReq = null;
        StdTx response = api.followupComment(followupCommentReq);

        // TODO: test validations
    }
    
    /**
     * Post a new comment to open a new thread
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void newThreadTest() throws ApiException {
        NewThreadReq newThreadReq = null;
        StdTx response = api.newThread(newThreadReq);

        // TODO: test validations
    }
    
    /**
     * reward some comments with coins
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rewardCommentsTest() throws ApiException {
        RewardCommentsReq rewardCommentsReq = null;
        StdTx response = api.rewardComments(rewardCommentsReq);

        // TODO: test validations
    }
    
}
